networks:
  currency-network:
    driver: bridge

services:
  currency-exchange:
    image: currency-exchange
    container_name: currency-exchange
    build:
      context: ./currency-exchange-service
      dockerfile: Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin-server:9411/api/v2/spans
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server

  currency-conversion:
    image: currency-conversion
    container_name: currency-conversion
    build:
      context: ./currency-conversion-service
      dockerfile: Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin-server:9411/api/v2/spans
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin-server:9411/api/v2/spans
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server

  naming-server:
    image: naming-server
    container_name: naming-server
    build:
      context: ./naming-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - currency-network

  zipkin-server:
    image: openzipkin/zipkin:2.23
    ports:
      - "9411:9411"
    networks:
      - currency-network
    restart: always